spring:
  profiles:
    active: dev
  application:
    name: user-center
  session:
    timeout: 86400
    # 默认是none 存储在服务器 redis: 表示存储在Redis，也是在Redis中读取
    store-type: redis

#Datasource config
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yang-user?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=Asia/Shanghai
    username: root
    password: 1821939eats
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

#  redis 配置
  redis:
    port: 6379
    host: localhost
    database: 0
    redissonDataBase: 3
    # 链接超时时间
    connect-timeout: 10s
    #lettuce连接池配置
    lettuce:
      pool:
        # 链接池中最小的空闲链接 默认为0
        min-idle: 0
        # 链接池中最大的空闲连接 默认为 8
        max-idle: 8
        #连接池中最大数据库链接数 默认为8
        max-active: 8
        #连接池最大阻塞等待时间 负值表示没有限制
        max-wait: -1ms
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #开启sql日志
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
server:
  port: 8080
  servlet:
    context-path:  /api


